[features]
seeds = false
skip-lint = false

[programs.localnet]
token_registry = "D9sdckhuzcYcGxyyMTwtmW4y5j5FPEa8nQbtprHr6z95"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mocchaust64/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
generate-types = "anchor-client-gen target/idl/token_registry.json target/types/token_registry.ts"

[test]
startup_wait = 10000
[toolchain]
anchor_version = "0.30.1"